version: 2.1

orbs:
    node: circleci/node@4.5

commands:
    install_and_cache_yarn_linux:
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
                  include-branch-in-cache-key: false
            - run: rm /tmp/node-project-package.json
            - run: rm /tmp/node-project-lockfile
    build-plugin:
        steps:
            - run: yarn build
    run-plugin-tests:
        steps:
            - run: yarn test:ci
    build-gatsby-2:
        steps:
            - node/install-packages:
                  pkg-manager: yarn
                  include-branch-in-cache-key: false
                  cache-version: gatsby2
                  app-dir: ~/project/test-installs/gatsby2
            - run:
                name: Build Gatsby 2.x.x
                command: cd ~/project/test-installs/gatsby2 && yarn build
    build-gatsby-3:
        steps:
            - node/install-packages:
                  pkg-manager: yarn
                  include-branch-in-cache-key: false
                  cache-version: gatsby3
                  app-dir: ~/project/test-installs/gatsby3
            - run:
                name: Build Gatsby 3.x.x
                command: cd ~/project/test-installs/gatsby3 && yarn build


# based on https://github.com/nodejs/Release schedule
jobs:
    Node v10 Plugin Tests:
        docker:
            - image: circleci/node:10
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - run-plugin-tests
    Node v12 Plugin Tests:
        docker:
            - image: circleci/node:12
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - run-plugin-tests
    Node v12 Gatsby 2:
        docker:
            - image: circleci/node:12
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - build-gatsby-2
    Node v12 Gatsby 3:
        docker:
            - image: circleci/node:12
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - build-gatsby-3
    Node v14 Plugin Tests:
        docker:
            - image: circleci/node:14
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - run-plugin-tests
    Node v14 Gatsby 2:
        docker:
            - image: circleci/node:14
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - build-gatsby-2
    Node v14 Gatsby 3:
        docker:
            - image: circleci/node:14
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - build-gatsby-3
    Node v14_16 Plugin Tests:
        docker:
            - image: circleci/node:14.16.0
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - run-plugin-tests
    Node v14_16 Gatsby 2:
        docker:
            - image: circleci/node:14.16.0
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - build-gatsby-2
    Node v14_16 Gatsby 3:
        docker:
            - image: circleci/node:14.16.0
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - build-gatsby-3
    Node v16 Plugin Tests:
        docker:
            - image: circleci/node:16
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - run-plugin-tests
    Node v16 Gatsby 2:
        docker:
            - image: circleci/node:16
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - build-gatsby-2
    Node v16 Gatsby 3:
        docker:
            - image: circleci/node:16
        steps:
            - install_and_cache_yarn_linux
            - build-plugin
            - build-gatsby-3
    Linting:
        docker:
            - image: circleci/node:14.16.0
        steps:
            - install_and_cache_yarn_linux
            - run:
                name: yarn lint
                command: yarn lint
workflows:
    main:
        jobs:
            - Linting
            - Node v10 Plugin Tests:
                requires:
                    - Linting
            - Node v12 Plugin Tests:
                requires:
                    - Linting
            - Node v12 Gatsby 2:
                requires:
                    - Node v12 Plugin Tests
            - Node v12 Gatsby 3:
                requires:
                    - Node v12 Plugin Tests
            - Node v14 Plugin Tests:
                requires:
                    - Linting
            - Node v14 Gatsby 2:
                requires:
                    - Node v14 Plugin Tests
            - Node v14 Gatsby 3:
                requires:
                    - Node v14 Plugin Tests
            - Node v14_16 Plugin Tests:
                requires:
                    - Linting
            - Node v14_16 Gatsby 2:
                requires:
                    - Node v14_16 Plugin Tests
            - Node v14_16 Gatsby 3:
                requires:
                    - Node v14_16 Plugin Tests
            - Node v16 Plugin Tests:
                requires:
                    - Linting
            - Node v16 Gatsby 2:
                requires:
                    - Node v16 Plugin Tests
            - Node v16 Gatsby 3:
                requires:
                    - Node v16 Plugin Tests
